# Generated by Django 5.2.6 on 2025-10-03 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_students'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Students',
            new_name='Student',
        ),
    ]
